In [2]:
import numpy as np

In [3]:
# version
np.__version__

'2.2.6'

In [ ]:
np.show_config()

In [12]:
# what is a null vector?
""""A null vector (also called a zero vector) is a vector in which all elements are zero.
It’s commonly used in linear algebra and programming for initialization or as a default placeholder."""

null_vector = np.zeros((5,5))
null_vector

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# memory_size
memory_size = np.zeros((10,10))
memory_size.size

100

In [6]:
# shape
a = np.array(([1, 2, 3],[4, 5, 6]))
a.shape

(2, 3)

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [12]:
# indexing
print(a[0])

1


In [ ]:

a[0] = 10
a

array([10,  2,  3,  4,  5,  6])