In [2]:
# How to import NumPy
import numpy as np

In [ ]:
# shape
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

In [ ]:
# Why use NumPy?
# 1. Fixed Type: faster to read less bytes of memory
# 2. Contiguous memory - Single Instruction Multiple Data (SIMD) Vector Processing & Effective Cache Utilization

In [ ]:
# What is an “array”?
# structure for storing and retrieving data

In [ ]:
# Array fundamentals
a = np.array([1, 2, 3, 4, 5, 6]) # using a python sequence, such as a list
a

array([1, 2, 3, 4, 5, 6])

In [6]:
# Elements of an array can be accessed in various ways
a[0]

np.int64(1)

In [14]:
# array is mutable.
a[0] = 10
a

array([10,  2,  3, 40,  5,  6])

In [13]:
# python slice notation can be used for indexing
a[:3]

array([10,  2,  3])

One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [12]:
b = a[3:]
b

array([40,  5,  6])

In [ ]:
b[0] = 40
a
a

In [15]:
list_a = [1,  2,  3, 4,  5,  6]
list_a 

[1, 2, 3, 4, 5, 6]

In [17]:
list_b = list_a[3:]
list_b

[4, 5, 6]

In [18]:
list_b[0] = 40
list_b

[40, 5, 6]

In [19]:
list_a

[1, 2, 3, 4, 5, 6]

Another difference between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square brackets, separated by commas. 

In [22]:
# Two- and higher-dimensional arrays can be initialized from nested Python sequences
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
print(a[1,3])

8


In [23]:
list_c = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
list_c[1][3]

8

In [26]:
# Array attributes
a.ndim

2